### PR TITLE
Using stable discovery and make sure we have message factories.

### PR DESCRIPTION
**Pull request by Nyholm**

### CODE REVIEW

**Comment by robojamison** [comment]
Can you help me understand why message factories are desired here?

**Comment by Nyholm** [comment]
One need message factories to actually create HTTP request. I've added a block in the readme about it. 

I also updated some other code. A user does not need to use the CURL client. He/She may install Guzzle or Buzz if they want to.

**Comment by robojamison** [comment]
Lovely. Thanks very much for the info. The update to the README was a nice touch.

**Comment by Nyholm** [comment]
You are welcome

**Pull request merged**
